### PR TITLE
Rubocop styling for Android tests

### PR DESCRIPTION
**Pull request by JaniJegoroff**
`rubocop` styling applied for Android tests and number of offences reduced from **80** to **0**.

All Android tests passed:
(tests are a bit flaky so they were executed in two parts)
> Finished in 3 mins 9 secs
> 103 runs, 144 assertions, 0 failures, 0 errors, 0 skips

> Janis-iMac:android_tests janijegoroff$ rake android[common/device_touchaction]
> Finished in 7 secs
> 3 runs, 0 assertions, 0 failures, 0 errors, 0 skips

### CODE REVIEW

**Comment by bootstraponline** [comment]
Awesome!

**Comment by bootstraponline** [comment]
@JaniJegoroff For Travis, we need the root Rakefile to run rubocop on everything. I fixed that in [this commit](https://github.com/appium/ruby_lib/commit/93cb8a59aa7f4fb0b398aa67cd5b93b6e34534b2). I'm impressed that rubocop is finding a bunch of issues in the code, some of which are real bugs (for example `===` instead of `==`).

**Comment by bootstraponline** [comment]
> (tests are a bit flaky so they were executed in two parts)

If you do `flake 3 android` then it'll try each test up to 3 times. If it succeeds once then it moves on. The flakiness is in the appium server so there's not too much we can do on the Ruby side other than retry failures.

**Comment by JaniJegoroff** [comment]
Cool, looks good. Rubocop is very useful tool indeed.

**Comment by JaniJegoroff** [comment]
@bootstraponline 

> (tests are a bit flaky so they were executed in two parts)

> If you do flake 3 android then it'll try each test up to 3 times. If it succeeds once then it moves on. The flakiness is in the appium server so there's not too much we can do on the Ruby side other than retry failures.

Looks like Appium server is working fine. I spent some time with Android tests today and found a simple fix to make them stable. So far tests are passing every time on Emulator (Intel HAXM) without using `flaky` gem. I will provide PR soon.

**Pull request merged**
