### PR TITLE
separate find_element/s for uiautomator and xpath

### PR DESCRIPTION
**Pull request by KazuCocoa**
fix: 9.4.0 release sudden failures #546

> I'll change to use uiautomation for appium automation name and xpath for uiautomator2.

ref- https://github.com/appium/ruby_lib/pull/544/files

---

- [x] run tests, find elements retaled, for appium and uiautomator2 strategy
- [ ] refactor

### CODE REVIEW

**Comment by Edouard-chin** [comment]
Thanks for fixing the issue <3

**Comment by KazuCocoa** [comment]
@Edouard-chin Could you run this branch?
I think this branch works fine for Appium strategy, `automationName`, with `:uiautomator` strategy.

**Comment by Edouard-chin** [comment]
@KazuCocoa I setup our CI to target this branch, will let you know the results after few builds

**Comment by Edouard-chin** [comment]
Ran our automation 4 times, one failed.

```ruby
appium_driver.button('Done').click
```

<details>
  <summary>Appium logs</summary>
[HTTP] --> POST /wd/hub/session/06e737c1-640a-4ba3-b2d7-cf5822c3aad3/element {"using":"xpath","value":"//android.widget.Button[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]|android.widget.ImageButton[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.Button[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]|android.widget.ImageButton[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]","06e737c1-640a-4ba3-b2d7-cf5822c3aad3"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.Button[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]|android.widget.ImageButton[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.Button[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]|android.widget.ImageButton[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.Button[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]|android.widget.ImageButton[contains(translate(@text,'DONE', 'Done'), 'Done') or contains(translate(@content-desc,'DONE', 'Done'), 'Done')]' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"Could not find an element using supplied strategy. "}
</details>


Screenshot when it failed 
screen shot 2017-04-17 at 9 12 47 pm

**Comment by KazuCocoa** [comment]
I forgot checking automationName for `button` method 3aa87a9...
@Edouard-chin Could you try again?

I also check this PR carefully after my work.

**Comment by Edouard-chin** [comment]
Ran the automation 8 times and no failures. I think it's working correctly. Nice work 🎉

**Comment by KazuCocoa** [comment]
Thanks!

**Comment by Edouard-chin** [comment]
For my own curiosity, why does the `:xpath` way of finding element works only 50% of the time?

**Comment by KazuCocoa** [comment]
I don't know well...
It depends on drivers, https://github.com/appium/appium-android-driver and https://github.com/appium/appium-uiautomator2-server, or Android OS side features, I guess.


@jlipps Do you know the reason why XPath is unstable than UIAutomator for Android?
Java client uses only xpath strategy to find elements. Does it work stable?
cc @TikhomirovSergey @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I cannot say anything for sure without having logs and page sources.

**Pull request merged**
