### PR TITLE
Case sensitive exact

### PR DESCRIPTION
**Pull request by KazuCocoa**
# Summary

Closes https://github.com/appium/ruby_lib/issues/852#issuecomment-464940768

# How Has This Been Tested?

- [x] run `rake ios['ios/element/text']`

# Checklist

- [x] `bundle exec rake rubocop`

### CODE REVIEW

**Comment by vitalyk** [comment]
@KazuCocoa when do you plan to release this fix?

**Comment by KazuCocoa** [comment]
will do

**Comment by vitalyk** [comment]
thank you

**Comment by KazuCocoa** [comment]
My pleasure. Thanks for your report!

**Pull request merged**
