### PR TITLE
refactor: loading xcuitest related methods only for XCUITest case

### PR DESCRIPTION
**Pull request by KazuCocoa**
Eliminate global driver to enable multi-device automation within a single process #312

- [x] run tests for iOS

### CODE REVIEW

**Comment by saikrishna321** [comment]
Is this possible with latest server ? Single server session which can handle multiple driver instances ??

**Comment by KazuCocoa** [comment]
If we use instance `@driver`, not a global driver, we perhaps can conduct multiple instances for iOS. Tough, I'm trying to check the behaviour with test scenarios before next release.

**Comment by saikrishna321** [comment]
@KazuCocoa will wait to hear from you on this

**Comment by KazuCocoa** [comment]
@saikrishna321 

Sorry for miss the comment. 😞 

If we use don't use the global driver, means don't use `promote_appium_methods` and `promote_singleton_appium_methods`, I think we can handle multiple driver instances with current master ruby_lib.
And I'm working to reduce or move the global driver more on [this issue](https://github.com/appium/ruby_lib/issues/312) and plan to prepare test cases running on multiple instances by Xcode 11.

**Comment by saikrishna321** [comment]
@KazuCocoa 
>I think we can handle multiple driver instances with current master ruby_lib

Agree this is possible, but is this possible to with Single appium server session ?

**Comment by KazuCocoa** [comment]
Sorry, I'm a bit confusing 🙇 
Which is the single appium server, the following's 1 or 2?

1.
```
@driver 1(thread 1) ---session1---- single appium server----devices
@driver 2(thread 2) ----session2----/
```

2.
```
@driver 1(thread 1) ----session1--- single appium server----devices
                  \-------session2------/
```

I guess `1` is possible but `2` is not.
But I'm not sure `1` is possible completely because I haven't implemented such case.

And 

> prepare test cases running on multiple instances by Xcode 11

I commented means I'll try to implement a test case like https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/parallel/parallel-simulators-e2e-specs.js

**Pull request merged**
