### PR TITLE
Use uiautomator for uiautomator2

### PR DESCRIPTION
**Pull request by KazuCocoa**
- ref:
    - investigate find_element/find_elements for uiautomator2 #560 
    - https://github.com/appium/ruby_lib/pull/547
    - fix button_exact, text_exact for uiautomator2 driver #543

To improve stability.

All tests associated with this change are greened.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Hi @Edouard-chin and @rajdeepv,

I've tried to use `uiautomator` strategy for finding elements which I fixed before.
Could you try this branch if you have a time?
If @Edouard-chin's [previous comment](https://github.com/appium/ruby_lib/pull/547#issuecomment-294650138)'s flakiness comes from xpath strategy, this PR will fix it, I think.

**Comment by Edouard-chin** [comment]
Will be able to try later today !

**Comment by KazuCocoa** [comment]
Thanks so much!

**Comment by rajdeepv** [comment]
I am still in process of migrating to uiautomator2. I will try to use this branch for few tests
Thanks

**Comment by Edouard-chin** [comment]
Sorry for the delay. I just tried your by running 10 automations, none of them failed 👍 .

**Comment by KazuCocoa** [comment]
Thanks!
I'll try this branch in my environment today, and I'll merge and release this if I have no failers.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/releases/tag/v9.4.3

**Comment by Edouard-chin** [comment]
👍

**Pull request merged**
